name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  fast-checks:
    name: Format, Lint & TypeScript
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://user:pass@localhost:5432/rival?schema=public

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Prisma Generate
        run: npx prisma generate

      - name: Prettier
        run: npm run format:check

      - name: ESLint
        run: npm run lint

      - name: TypeScript
        run: npm run typecheck

  slow-checks:
    name: Tests & Build
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://user:pass@localhost:5432/rival?schema=public

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Prisma Generate
        run: npx prisma generate

      - name: Tests
        run: npm run test:coverage

      - name: Build
        run: npm run build
